### ISSUE TITLE
RSS feed formatting

### ISSUE THREAD

**Issue by gizmecano** [rachsmithcodes/rachsmith.com#2]
Greetings,

This is probably more of a question than a issue (by the way very minor), but I wonder if there is a specific reason for not using the standard format for your RSS feed?

https://github.com/rachsmithcodes/rachsmith.com/blob/4b403140735ba94349e41ec84c03fbbba2ea0767/src/components/HomeHeader.astro#L235

Indeed, for some visitors who do not use Feedly (as I do), your feed does not seem to be properly detected (while the standard feed[^1] works perfectly well).

[^1]: https://rachsmith.com/rss/

**Comment by rachsmithcodes** [comment]
hi @gizmecano, thanks for the question. Yeah I added the feedly link originally for the convenience factor but it probably just inconveniences people who don't use feedly. I'm going to change it to the plain feed link.
