### ISSUE TITLE
Cannot scroll when mouse is on the right side of screen

### ISSUE THREAD

**Issue by zachpmanson** [rachsmithcodes/rachsmith.com#9]
### Issue Summary

Firefox 118.0.2, Ubuntu 22.04

### To Reproduce

Website won't scroll if the mouse is on the right side.

**Comment by rachsmithcodes** [comment]
Hi Zach, thanks for reporting! This should resolved after [this commit](https://github.com/rachsmithcodes/rachsmith.com/commit/a9ace107971906eef82e9bc19edd58bc0e7aefee). Cheers
